import PDFDocument from 'pdfkit';
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';

import { TranscriptionEntry } from '../types';

export async function pdfGenerator(transcriptions: (string | TranscriptionEntry)[]): Promise<string> {
  // Ensure the logs directory exists
  const logsDir = path.join(process.cwd(), ".logs", "pdfs");
  if (!fs.existsSync(logsDir)) {
    fs.mkdirSync(logsDir, { recursive: true });
  }

  // Create a temporary file in the logs directory
  const pdfFilePath = path.join(logsDir, `transcription-${Date.now()}.pdf`);

  // Create PDF document
  const doc = new PDFDocument({
    size: 'A4',
    margins: { top: 72, bottom: 72, left: 36, right: 36 }
  });

  // Pipe to file
  const stream = fs.createWriteStream(pdfFilePath);
  doc.pipe(stream);

  // Add background image if available
  const backgroundPath = path.join(process.cwd(), 'assets', 'parchment_background.jpg');
  if (fs.existsSync(backgroundPath)) {
    doc.image(backgroundPath, 0, 0, { width: 612, height: 792 });
  }

  // Title
  doc.fontSize(24)
    .font('Helvetica-Bold')
    .fillColor('darkred')
    .text('Transcription Report', { align: 'center' })
    .moveDown(2);

  // Column headers
  doc.fontSize(10)
    .font('Courier')
    .fillColor('black')
    .text('Begin', 36, 120)
    .text('Character', 150, 120)
    .text('Data', 280, 120);

  // Divider line
  doc.moveTo(36, 135)
    .lineTo(576, 135)
    .stroke()
    .moveDown(1);

  let yPosition = 150;

  // Add transcriptions
  for (const logMessage of transcriptions) {
    let entry: TranscriptionEntry;
    
    if (typeof logMessage === 'string') {
      try {
        entry = JSON.parse(logMessage);
      } catch (e) {
        continue;
      }
    } else {
      entry = logMessage;
    }

    const begin = entry.begin || "N/A";
    const character = entry.character || "N/A";
    const data = entry.data || "";

    if (!data) {
      continue;
    }

    // Check if we need a new page
    if (yPosition > 700) {
      doc.addPage();
      if (fs.existsSync(backgroundPath)) {
        doc.image(backgroundPath, 0, 0, { width: 612, height: 792 });
      }
      yPosition = 72;
    }

    // Format entry
    doc.fontSize(10)
      .font('Courier')
      .fillColor('black')
      .text(`${begin}`, 36, yPosition)
      .text(`${character}:`, 150, yPosition)
      .text(data, 280, yPosition, { width: 300, align: 'left' });

    yPosition += 20;
  }

  // Watermark
  doc.fontSize(8)
    .font('Helvetica')
    .fillColor('gray')
    .text('Generated by V.O.L.O', 36, 750, { align: 'left' });

  // Finalize PDF
  doc.end();

  // Wait for stream to finish
  return new Promise((resolve, reject) => {
    stream.on('finish', () => {
      resolve(pdfFilePath);
    });
    stream.on('error', reject);
  });
}

